services:
  schedule:
    build: ..
    environment:
      TZ: Europe/Stockholm
    volumes:
      - ./config.json:/app/config.json
      - ./calendars.json:/app/calendars.json
      - calendars:/app/calendars
  nginx:
    image: nginx:alpine3.20
    environment:
      TZ: Europe/Stockholm
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./xslt.xml:/etc/nginx/xslt.xml
      - calendars:/var/calendars

volumes:
  calendars:
